parameters:
#    tratamiento.example.class: Neurologia\TratamientoBundle\Example

services:
#    tratamiento.example:
#        class: %tratamiento.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
