estadocivil:
    path:     /
    defaults: { _controller: "NeurologiaGenericosBundle:EstadoCivil:index" }

estadocivil_show:
    path:     /{id}/show
    defaults: { _controller: "NeurologiaGenericosBundle:EstadoCivil:show" }

estadocivil_new:
    path:     /new
    defaults: { _controller: "NeurologiaGenericosBundle:EstadoCivil:new" }

estadocivil_create:
    path:     /create
    defaults: { _controller: "NeurologiaGenericosBundle:EstadoCivil:create" }
    requirements: { _method: post }

estadocivil_edit:
    path:     /{id}/edit
    defaults: { _controller: "NeurologiaGenericosBundle:EstadoCivil:edit" }

estadocivil_update:
    path:     /{id}/update
    defaults: { _controller: "NeurologiaGenericosBundle:EstadoCivil:update" }
    requirements: { _method: post|put }

estadocivil_delete:
    path:     /{id}/delete
    defaults: { _controller: "NeurologiaGenericosBundle:EstadoCivil:delete" }
    requirements: { _method: post|delete }
