niveleducacional:
    path:     /
    defaults: { _controller: "NeurologiaGenericosBundle:NivelEducacional:index" }

niveleducacional_show:
    path:     /{id}/show
    defaults: { _controller: "NeurologiaGenericosBundle:NivelEducacional:show" }

niveleducacional_new:
    path:     /new
    defaults: { _controller: "NeurologiaGenericosBundle:NivelEducacional:new" }

niveleducacional_create:
    path:     /create
    defaults: { _controller: "NeurologiaGenericosBundle:NivelEducacional:create" }
    requirements: { _method: post }

niveleducacional_edit:
    path:     /{id}/edit
    defaults: { _controller: "NeurologiaGenericosBundle:NivelEducacional:edit" }

niveleducacional_update:
    path:     /{id}/update
    defaults: { _controller: "NeurologiaGenericosBundle:NivelEducacional:update" }
    requirements: { _method: post|put }

niveleducacional_delete:
    path:     /{id}/delete
    defaults: { _controller: "NeurologiaGenericosBundle:NivelEducacional:delete" }
    requirements: { _method: post|delete }
