tipodocumento:
    path:     /
    defaults: { _controller: "NeurologiaGenericosBundle:TipoDocumento:index" }

tipodocumento_show:
    path:     /{id}/show
    defaults: { _controller: "NeurologiaGenericosBundle:TipoDocumento:show" }

tipodocumento_new:
    path:     /new
    defaults: { _controller: "NeurologiaGenericosBundle:TipoDocumento:new" }

tipodocumento_create:
    path:     /create
    defaults: { _controller: "NeurologiaGenericosBundle:TipoDocumento:create" }
    requirements: { _method: post }

tipodocumento_edit:
    path:     /{id}/edit
    defaults: { _controller: "NeurologiaGenericosBundle:TipoDocumento:edit" }

tipodocumento_update:
    path:     /{id}/update
    defaults: { _controller: "NeurologiaGenericosBundle:TipoDocumento:update" }
    requirements: { _method: post|put }

tipodocumento_delete:
    path:     /{id}/delete
    defaults: { _controller: "NeurologiaGenericosBundle:TipoDocumento:delete" }
    requirements: { _method: post|delete }
