neurologia_first_homepage:
    path:     /index
    defaults: { _controller: NeurologiaFirstBundle:Default:index }
neurologia_first_backend:
    path:     /index/backend/{name}
    defaults: { _controller: NeurologiaFirstBundle:Default:backend }
neurologia_first_login:
    path:     /login
    defaults: { _controller: NeurologiaFirstBundle:Default:login }
neurologia_first_logout:
    path:     /logout
    defaults: { _controller: NeurologiaFirstBundle:Default:login }
neurologia_first_admin:
    path:     /admin/index
    defaults: { _controller: NeurologiaFirstBundle:Default:backend }