Neurologia\DBBundle\Entity\Motivo:
    properties:
        id:
            - NotBlank: ~
            - Type: integer
            - Length:
                min: 1
                max: 11
                minMessage: "Your first name must be at least {{ limit }} characters long"
                maxMessage: "Your first name cannot be longer than {{ limit }} characters long"
        fecha:
            - NotBlank: ~
            - Type: 
                tipe: Date
                message: The value {{ value }} is not a valid {{ type }}.
        detalle:
            - NotBlank: ~
            - Type:
                type: alpha
                message: The value {{ value }} is not a valid {{ type }}.
            - Length:
                min: 2
                max: 50
                minMessage: "Your first name must be at least {{ limit }} characters long"
                maxMessage: "Your first name cannot be longer than {{ limit }} characters long"
        usuario:
            - NotBlank: ~
        historiaClinica:
            - NotBlank: ~