neurologia_pacientes:
    resource: "@NeurologiaPacientesBundle/Resources/config/routing.yml"
    prefix:   /

neurologia_estudio:
    resource: "@NeurologiaEstudioBundle/Resources/config/routing.yml"
    prefix:   /

neurologia_diagnostico:
    resource: "@NeurologiaDiagnosticoBundle/Resources/config/routing.yml"

neurologia_antecedente:
    resource: "@NeurologiaAntecedenteBundle/Resources/config/routing.yml"

neurologia_tratamiento:
    resource: "@TratamientoBundle/Resources/config/routing.yml"

neurologia_historia_clinica:
    resource: "@NeurologiaHistoriaClinicaBundle/Resources/config/routing.yml"
    prefix:   /

neurologia_main:
    resource: "@NeurologiaMainBundle/Resources/config/routing.yml"
    prefix:   /

neurologia_genericos:
    resource: "@NeurologiaGenericosBundle/Resources/config/routing.yml"
    prefix:   /

neurologia_user:
    resource: "@NeurologiaUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

neurologia_bd:
    resource: "@NeurologiaBDBundle/Resources/config/routing.yml"
    prefix:   /
