security:
    access_denied_url: /login
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_SECRETARY:        ROLE_USER
        ROLE_DOCTOR:           ROLE_SECRETARY
        ROLE_ADMIN:            ROLE_DOCTOR
        ROLE_SUPER_ADMIN:      [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /home
            logout:       true
            anonymous:    true
    access_control:
        
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN  }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, role: [ROLE_ADMIN, ROLE_DOCTOR, ROLE_SECRETARY] }
        - { path: ^/abm, role: ROLE_ADMIN }
        - { path: ^/tratamiento, role: [ROLE_ADMIN, ROLE_DOCTOR] }
        - { path: ^/evolucion, role: [ROLE_ADMIN, ROLE_DOCTOR] }
        - { path: ^/home, role: [ROLE_ADMIN, ROLE_DOCTOR, ROLE_SECRETARY] }
        - { path: ^/busqueda/paciente, role: [ROLE_ADMIN, ROLE_DOCTOR, ROLE_SECRETARY] }
        - { path: ^/busqueda/usuario, role: [ROLE_ADMIN, ROLE_DOCTOR] }
        - { path: ^/busqueda/avanzada, role: [ROLE_ADMIN, ROLE_DOCTOR] }
        - { path: ^/historia, role: [ROLE_ADMIN, ROLE_DOCTOR] }
        - { path: ^/admin, role: ROLE_ADMIN }
