neurologia_register:
    path:     /register
    defaults: { _controller: FOSUserBundle:Registration:register }

neurologia_login:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

user:
    path:     /user/
    defaults:  
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

user_edit:
    path:     /user/{id}/edit
    defaults: { _controller: "NeurologiaUserBundle:User:edit" }
    
user_update:
    path:     /user/{id}/update
    defaults: { _controller: "NeurologiaUserBundle:User:update" }
    requirements: { _method: post|put }
    
admin:
    path:     /admin/
    defaults:  
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

admin_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "NeurologiaUserBundle:Admin:edit" }

admin_update:
    path:     /admin/{id}/update
    defaults: { _controller: "NeurologiaUserBundle:Admin:update" }
    requirements: { _method: post|put }
