neurologia_admin_homepage:
    path:     /admin
    defaults: { _controller: NeurologiaUserBundle:Default:admin }
    
neurologia_user_homepage:
    path:     /user
    defaults: { _controller: NeurologiaUserBundle:Default:user }

neurologia_register:
    path:     /register
    defaults: { _controller: FOSUserBundle:Registration:register }

neurologia_login:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }
    
neurologia_agregar_usuario:
    path:     /admin/agregarUsuario
    defaults: { _controller: NeurologiaUserBundle:Default:agregarUsuario }