neurologia_register:
    path:     /register
    defaults: { _controller: FOSUserBundle:Registration:register }

neurologia_login:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }
    
neurologia_agregar_usuario:
    path:     /admin/agregarUsuario
    defaults: { _controller: NeurologiaUserBundle:Default:agregarUsuario }
    
user:
    path:     /admin/
    defaults: { _controller: "NeurologiaUserBundle:User:index" }

user_show:
    path:     /admin/{id}/show
    defaults: { _controller: "NeurologiaUserBundle:User:show" }

user_new:
    path:     /admin/new
    defaults: { _controller: "NeurologiaUserBundle:User:new" }

user_create:
    path:     /admin/create
    defaults: { _controller: "NeurologiaUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "NeurologiaUserBundle:User:edit" }

user_update:
    path:     /admin/{id}/update
    defaults: { _controller: "NeurologiaUserBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "NeurologiaUserBundle:User:delete" }
    requirements: { _method: post|delete }
