diagnostico_listar:
    path:     /diagnostico
    defaults: { _controller: NeurologiaDiagnosticoBundle:Default:index }

diagnostico_nuevo:
    path:     /diagnostico/nuevo
    defaults: { _controller: NeurologiaDiagnosticoBundle:Default:new }

diagnostico_borrar:
    path:     /diagnostico/borrar/{key}
    defaults: { _controller: NeurologiaDiagnosticoBundle:Default:delete }
    
diagnostico_editar:
    path:     /diagnostico/editar/{key}
    defaults: { _controller: NeurologiaDiagnosticoBundle:Default:edit }