parameters:
#    neurologia_diagnostico.example.class: Neurologia\DiagnosticoBundle\Example

services:
#    neurologia_diagnostico.example:
#        class: %neurologia_diagnostico.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
