neurologia_busqueda_homepage:
    path:     /busqueda
    defaults: { _controller: NeurologiaBusquedaBundle:Default:index }
neurologia_busqueda_paciente:
    path:     /busqueda/paciente
    defaults: { _controller: NeurologiaBusquedaBundle:Default:paciente }
neurologia_busqueda_usuario:
    path:     /busqueda/usuario
    defaults: { _controller: NeurologiaBusquedaBundle:Default:usuario }
neurologia_busqueda_avanzada:
    path:     /busqueda/avanzada
    defaults: { _controller: NeurologiaBusquedaBundle:Default:avanzada }