parameters:
#    neurologia_busqueda.example.class: Neurologia\BusquedaBundle\Example

services:
#    neurologia_busqueda.example:
#        class: %neurologia_busqueda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
