estudio_nuevo:
    path:     /estudio/nuevo
    defaults: { _controller: NeurologiaEstudioBundle:Default:nuevo }
    
estudio_success:
    path:     /estudio/success
    defaults: { _controller: NeurologiaEstudioBundle:Default:success }

estudio_listar:
    path:     /estudio/listar
    defaults: { _controller: NeurologiaEstudioBundle:Default:listar }
    
estudio_show:
    path:     /estudio/{id}/show
    defaults: { _controller: "NeurologiaEstudioBundle:Default:show" }
    
estudio_borrar:
    path:     /estudio/{key}/borrar
    defaults: { _controller: "NeurologiaEstudioBundle:Default:delete" }
    
estudio_editar:
    path:     /estudio/{key}/editar
    defaults: { _controller: "NeurologiaEstudioBundle:Default:edit" }
        