antecedente:
    path:     /
    defaults: { _controller: "NeurologiaAntecedenteBundle:Antecedente:index" }

antecedente_show:
    path:     /{id}/show
    defaults: { _controller: "NeurologiaAntecedenteBundle:Antecedente:show" }

antecedente_new:
    path:     /new
    defaults: { _controller: "NeurologiaAntecedenteBundle:Antecedente:new" }

antecedente_create:
    path:     /create
    defaults: { _controller: "NeurologiaAntecedenteBundle:Antecedente:create" }
    requirements: { _method: post }

antecedente_edit:
    path:     /{id}/edit
    defaults: { _controller: "NeurologiaAntecedenteBundle:Antecedente:edit" }

antecedente_update:
    path:     /{id}/update
    defaults: { _controller: "NeurologiaAntecedenteBundle:Antecedente:update" }
    requirements: { _method: post|put }

antecedente_delete:
    path:     /{id}/delete
    defaults: { _controller: "NeurologiaAntecedenteBundle:Antecedente:delete" }
    requirements: { _method: post|delete }
