neurologia_historia_clinica_homepage:
    path:     /{idpaciente}/historia
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Default:index }
    
neurologia_historia_clinica_iniciar:
    path:     /{idpaciente}/historia/iniciar
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Default:iniciar }
    
neurologia_historia_clinica_motivo:
    path:     /historia/{id}/motivo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Motivo:index }

neurologia_historia_clinica_motivo_nuevo:
    path:   /historia/{id}/motivo/nuevo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Motivo:nuevo }
    
neurologia_historia_clinica_enfermedad:
    path:     /historia/{id}/enfermedad
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Enfermedad:index }
    
neurologia_historia_clinica_enfermedad_nuevo:
    path:   /historia/{id}/enfermedad/nuevo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Enfermedad:nuevo }
