neurologia_historia_clinica_homepage:
    path:     /historia
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Default:index }
    
neurologia_historia_clinica_iniciar:
    path:     /historia/iniciar
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Default:iniciar }
    
motivo_listar:
    path:     /historia/motivo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Motivo:index }

motivo_nuevo:
    path:   /historia/motivo/nuevo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Motivo:nuevo }
    
enfermedad_listar:
    path:     /historia/enfermedad
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Enfermedad:index }
    
enfermedad_nuevo:
    path:   /historia/enfermedad/nuevo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Enfermedad:nuevo }
    
neurologia_historia_clinica_epicrisis:
    path:     /epicrisis
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Default:epicrisis }
