neurologia_historia_clinica_homepage:
    path:     /historia
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Default:index }
    
neurologia_historia_clinica_iniciar:
    path:     /historia/iniciar
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Default:iniciar }
    
neurologia_historia_clinica_motivo:
    path:     /historia/motivo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Motivo:index }

neurologia_historia_clinica_motivo_nuevo:
    path:   /historia/motivo/nuevo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Motivo:nuevo }
    
neurologia_historia_clinica_enfermedad:
    path:     /historia/enfermedad
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Enfermedad:index }
    
neurologia_historia_clinica_enfermedad_nuevo:
    path:   /historia/enfermedad/nuevo
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Enfermedad:nuevo }
    
neurologia_historia_clinica_epicrisis:
    path:     /epicrisis
    defaults: { _controller: NeurologiaHistoriaClinicaBundle:Default:epicrisis }
