paciente:
    path:     /paciente
    defaults: { _controller: "NeurologiaPacientesBundle:Default:index" }

paciente_show:
    path:     /paciente/{id}/show
    defaults: { _controller: "NeurologiaPacientesBundle:Default:show" }

paciente_new:
    path:     /paciente/new
    defaults: { _controller: "NeurologiaPacientesBundle:Default:new" }

paciente_create:
    path:     /paciente/create
    defaults: { _controller: "NeurologiaPacientesBundle:Default:create" }
    requirements: { _method: post }

paciente_edit:
    path:     /paciente/{id}/edit
    defaults: { _controller: "NeurologiaPacientesBundle:Default:edit" }

paciente_update:
    path:     /paciente/{id}/update
    defaults: { _controller: "NeurologiaPacientesBundle:Default:update" }
    requirements: { _method: post|put }

paciente_delete:
    path:     /paciente/{id}/delete
    defaults: { _controller: "NeurologiaPacientesBundle:Default:delete" }
    requirements: { _method: post|delete }
