parameters:
#    neurologia_pacientes.example.class: Neurologia\PacientesBundle\Example

services:
#    neurologia_pacientes.example:
#        class: %neurologia_pacientes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
