Antecedente:
    type: entity
    table: antecedente
    indexes:
        FK_antecedente:
            columns:
                - tipo_antecedente_id
        FK_antecedente2:
            columns:
                - historia_clinica_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        historiaClinica:
            targetEntity: HistoriaClinica
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                historia_clinica_id:
                    referencedColumnName: id
            orphanRemoval: false
        tipoAntecedente:
            targetEntity: TipoAntecedente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_antecedente_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
