parameters:
#    neurologia_tabs.example.class: Neurologia\TabsBundle\Example

services:
#    neurologia_tabs.example:
#        class: %neurologia_tabs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
