parameters:
#    evolucion.example.class: Neurologia\EvolucionBundle\Example

services:
#    evolucion.example:
#        class: %evolucion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
